export const POST_LOGIN_REQUEST = 'POST_LOGIN_REQUEST';
export const POST_LOGIN_SUCCESS = 'POST_LOGIN_SUCCESS';
export const POST_LOGIN_FAILURE = 'POST_LOGIN_FAILURE';

export const ACCESS_CODE_REQUEST = "ACCESS_CODE_REQUEST";
export const ACCESS_CODE_SUCCESS = "ACCESS_CODE_SUCCESS";
export const ACCESS_CODE_FAILURE = "ACCESS_CODE_FAILURE";



export const RESEND_OTP_REQUEST = 'RESEND_OTP_REQUEST';
export const RESEND_OTP_SUCCESS = 'RESEND_OTP_SUCCESS';
export const RESEND_OTP_FAILURE = 'RESEND_OTP_FAILURE';


export const CLEAR_OTP = 'CLEAR_OTP';
export const CLEAR_ACCESSCODE_ERROR = 'CLEAR_ACCESSCODE_ERROR';
export const CLEAR_ACCESSCODE_STATUS = 'CLEAR_ACCESSCODE_STATUS';

// // src/Redux/Type_File/VendorType.js

// // Fetch
// export const FETCH_VENDORS_REQUEST = "FETCH_VENDORS_REQUEST";
// export const FETCH_VENDORS_SUCCESS = "FETCH_VENDORS_SUCCESS";
// export const FETCH_VENDORS_FAILURE = "FETCH_VENDORS_FAILURE";

// // Create
// export const CREATE_VENDOR_REQUEST = "CREATE_VENDOR_REQUEST";
// export const CREATE_VENDOR_SUCCESS = "CREATE_VENDOR_SUCCESS";
// export const CREATE_VENDOR_FAILURE = "CREATE_VENDOR_FAILURE";

// // Update
// export const UPDATE_VENDOR_REQUEST = "UPDATE_VENDOR_REQUEST";
// export const UPDATE_VENDOR_SUCCESS = "UPDATE_VENDOR_SUCCESS";
// export const UPDATE_VENDOR_FAILURE = "UPDATE_VENDOR_FAILURE";

// // Delete / Change Status
// export const DELETE_VENDOR_REQUEST = "DELETE_VENDOR_REQUEST";
// export const DELETE_VENDOR_SUCCESS = "DELETE_VENDOR_SUCCESS";
// export const DELETE_VENDOR_FAILURE = "DELETE_VENDOR_FAILURE";
