// // src/Redux/Type_File/Type.js

// // CREATE
// export const CREATE_VENDOR_REQUEST = "CREATE_VENDOR_REQUEST";
// export const CREATE_VENDOR_SUCCESS = "CREATE_VENDOR_SUCCESS";
// export const CREATE_VENDOR_FAILURE = "CREATE_VENDOR_FAILURE";

// // READ
// export const FETCH_VENDORS_REQUEST = "FETCH_VENDORS_REQUEST";
// export const FETCH_VENDORS_SUCCESS = "FETCH_VENDORS_SUCCESS";
// export const FETCH_VENDORS_FAILURE = "FETCH_VENDORS_FAILURE";

// // UPDATE
// export const UPDATE_VENDOR_REQUEST = "UPDATE_VENDOR_REQUEST";
// export const UPDATE_VENDOR_SUCCESS = "UPDATE_VENDOR_SUCCESS";
// export const UPDATE_VENDOR_FAILURE = "UPDATE_VENDOR_FAILURE";

// // DELETE
// export const DELETE_VENDOR_REQUEST = "DELETE_VENDOR_REQUEST";
// export const DELETE_VENDOR_SUCCESS = "DELETE_VENDOR_SUCCESS";
// export const DELETE_VENDOR_FAILURE = "DELETE_VENDOR_FAILURE";


export const VENDOR_UPDATE_REQUEST = 'VENDOR_UPDATE_REQUEST';
export const FETCH_SUCCESS = 'FETCH_SUCCESS';
export const FETCH_FAILURE = 'FETCH_FAILURE';

export const FETCH_INACTIVE_REQUEST = 'FETCH_INACTIVE_REQUEST';
export const FETCH_INACTIVE_SUCCESS = 'FETCH_INACTIVE_SUCCESS';
export const FETCH_INACTIVE_FAILURE = 'FETCH_INACTIVE_FAILURE';

export const MARK_INACTIVE_REQUEST = 'MARK_INACTIVE_REQUEST';
export const MARK_ACTIVE_REQUEST = 'MARK_ACTIVE_REQUEST';

export const FETCH_VENDOR_DETAILS_REQUEST = 'FETCH_VENDOR_DETAILS_REQUEST';
export const FETCH_CITIES_REQUEST = 'FETCH_CITIES_REQUEST';

export const CREATE_VENDOR_REQUEST = 'CREATE_VENDOR_REQUEST';
export const CREATE_VENDOR_SUCCESS = 'CREATE_VENDOR_SUCCESS';
export const CREATE_VENDOR_FAILURE = 'CREATE_VENDOR_FAILURE';
